# CLASS 23: PANDAS(CONCAT,JOIN,MERGE): 31 JULY 2022

Dataset Used: https://drive.google.com/file/d/1FRnbQqgK6S-mr9StNF5MurSaXhah9uoJ/view

![0_V0GyOt3LoDVfY7y5.png](https://files.realpython.com/media/Reading-and-Writing-Data-With-Pandas_Watermarked.435ef1c38466.jpg)



In [1]:
import pandas as pd

In [2]:
#Creating Dictionary
data = {'name' : ['sudh','krish','hitesh','tulesko'],
        'salary' : [100,200,300,400],
        'mail_id' : ['sudhanshu@ineuron.ai','krish@ineuron.ai','hitesh@ineuron.ai','tulesko@ineuron.ai'],
        'addr' : ['blr','blr','blr','mum']
        }

In [3]:
#Converting Dictionary into Dataframe
#If there is mismatch of number of elements in keys, then dataframe creation will show error
pd.DataFrame(data)

name  salary               mail_id addr
0     sudh     100  sudhanshu@ineuron.ai  blr
1    krish     200      krish@ineuron.ai  blr
2   hitesh     300     hitesh@ineuron.ai  blr
3  tulesko     400    tulesko@ineuron.ai  mum

In [4]:
#Giving own index names
df = pd.DataFrame(data,index=[4,5,6,7])

In [5]:
df.loc[5:6] #Give Named Indexes

name  salary            mail_id addr
5   krish     200   krish@ineuron.ai  blr
6  hitesh     300  hitesh@ineuron.ai  blr

In [6]:
df.iloc[5:6] #We need to give default indexes (0,1,2,3 etc) for iloc to work

Empty DataFrame
Columns: [name, salary, mail_id, addr]
Index: []

In [7]:
df.iloc[1:3] #Solved upper problem

name  salary            mail_id addr
5   krish     200   krish@ineuron.ai  blr
6  hitesh     300  hitesh@ineuron.ai  blr

In [8]:
df = pd.DataFrame(data,index=['sudh','krish','hitesh','tulesko'])
df

name  salary               mail_id addr
sudh        sudh     100  sudhanshu@ineuron.ai  blr
krish      krish     200      krish@ineuron.ai  blr
hitesh    hitesh     300     hitesh@ineuron.ai  blr
tulesko  tulesko     400    tulesko@ineuron.ai  mum

In [9]:
#Lets stick to original indexes
df = pd.DataFrame(data,index=[0,1,2,3])
df

name  salary               mail_id addr
0     sudh     100  sudhanshu@ineuron.ai  blr
1    krish     200      krish@ineuron.ai  blr
2   hitesh     300     hitesh@ineuron.ai  blr
3  tulesko     400    tulesko@ineuron.ai  mum

In [10]:
#New Dataframe Creation
data1 = {'pf_no' : [234,45,54465,656],
         'income_tax' : [234, 565, 767, 6778],
         'mobile_no' : [23543,43543,454,5656],
         'courses' : ['ds','bigdata','web dev','blockchain']
    
}

df1 = pd.DataFrame(data1)
df1

pf_no  income_tax  mobile_no     courses
0    234         234      23543          ds
1     45         565      43543     bigdata
2  54465         767        454     web dev
3    656        6778       5656  blockchain

In [11]:
#Horizontal Concatenation of dataframes 
pd.concat([df,df1]) 

name  salary               mail_id addr    pf_no  income_tax  mobile_no  \
0     sudh   100.0  sudhanshu@ineuron.ai  blr      NaN         NaN        NaN   
1    krish   200.0      krish@ineuron.ai  blr      NaN         NaN        NaN   
2   hitesh   300.0     hitesh@ineuron.ai  blr      NaN         NaN        NaN   
3  tulesko   400.0    tulesko@ineuron.ai  mum      NaN         NaN        NaN   
0      NaN     NaN                   NaN  NaN    234.0       234.0    23543.0   
1      NaN     NaN                   NaN  NaN     45.0       565.0    43543.0   
2      NaN     NaN                   NaN  NaN  54465.0       767.0      454.0   
3      NaN     NaN                   NaN  NaN    656.0      6778.0     5656.0   

      courses  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
0          ds  
1     bigdata  
2     web dev  
3  blockchain

In [12]:
df

name  salary               mail_id addr
0     sudh     100  sudhanshu@ineuron.ai  blr
1    krish     200      krish@ineuron.ai  blr
2   hitesh     300     hitesh@ineuron.ai  blr
3  tulesko     400    tulesko@ineuron.ai  mum

In [13]:
df1

pf_no  income_tax  mobile_no     courses
0    234         234      23543          ds
1     45         565      43543     bigdata
2  54465         767        454     web dev
3    656        6778       5656  blockchain

In [14]:
#Horizontal Concatenation
df = pd.DataFrame(data)
pd.concat([df,df1])

name  salary               mail_id addr    pf_no  income_tax  mobile_no  \
0     sudh   100.0  sudhanshu@ineuron.ai  blr      NaN         NaN        NaN   
1    krish   200.0      krish@ineuron.ai  blr      NaN         NaN        NaN   
2   hitesh   300.0     hitesh@ineuron.ai  blr      NaN         NaN        NaN   
3  tulesko   400.0    tulesko@ineuron.ai  mum      NaN         NaN        NaN   
0      NaN     NaN                   NaN  NaN    234.0       234.0    23543.0   
1      NaN     NaN                   NaN  NaN     45.0       565.0    43543.0   
2      NaN     NaN                   NaN  NaN  54465.0       767.0      454.0   
3      NaN     NaN                   NaN  NaN    656.0      6778.0     5656.0   

      courses  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
0          ds  
1     bigdata  
2     web dev  
3  blockchain

In [15]:
#Vertical Concatenation
pd.concat([df,df1],axis=1)

name  salary               mail_id addr  pf_no  income_tax  mobile_no  \
0     sudh     100  sudhanshu@ineuron.ai  blr    234         234      23543   
1    krish     200      krish@ineuron.ai  blr     45         565      43543   
2   hitesh     300     hitesh@ineuron.ai  blr  54465         767        454   
3  tulesko     400    tulesko@ineuron.ai  mum    656        6778       5656   

      courses  
0          ds  
1     bigdata  
2     web dev  
3  blockchain

In [16]:
data2 = {'0' : ['sudh','krish','hitesh','tulesko'],
        '1' : [100,200,300,400],
        '2' : ['sudhanshu@ineuron.ai','krish@ineuron.ai','hitesh@ineuron.ai','tulesko@ineuron.ai'],
        '3' : ['blr','blr','blr','mum']
        }
data3 = {'0' : [234,45,54465,656],
         '1' : [234, 565, 767, 6778],
         '2' : [23543,43543,454,5656],
         '3' : ['ds','bigdata','web dev','blockchain']
         }

df2 = pd.DataFrame(data2)
df3 = pd.DataFrame(data3)



In [17]:
pd.concat([df2,df3]) #If column name is same, then NAN values will not come and it will show complete vertical concat operation

0     1                     2           3
0     sudh   100  sudhanshu@ineuron.ai         blr
1    krish   200      krish@ineuron.ai         blr
2   hitesh   300     hitesh@ineuron.ai         blr
3  tulesko   400    tulesko@ineuron.ai         mum
0      234   234                 23543          ds
1       45   565                 43543     bigdata
2    54465   767                   454     web dev
3      656  6778                  5656  blockchain

In [18]:
#Merge Operation
data4 = {'emp_id': [101,102,103,104],
         'salary' : [234,345,200,400],
         'pf' : [23,34,56,78] 
         }

data5 = {'emp_id' : [101,102,104,105],
         'mob_no' : [3434,5656,767,878],
         'house_no' : [345,345,345,56]
         }

df4 = pd.DataFrame(data4)
df5 = pd.DataFrame(data5)
                   

In [19]:
pd.merge(df4,df5) #Basically performs inner join on Common Column (Emp_id)

emp_id  salary  pf  mob_no  house_no
0     101     234  23    3434       345
1     102     345  34    5656       345
2     104     400  78     767       345

In [20]:
pd.merge(df4,df5,how='left') #Left Join

emp_id  salary  pf  mob_no  house_no
0     101     234  23  3434.0     345.0
1     102     345  34  5656.0     345.0
2     103     200  56     NaN       NaN
3     104     400  78   767.0     345.0

In [21]:
pd.merge(df4,df5,how='right') #Right Join

emp_id  salary    pf  mob_no  house_no
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [22]:
pd.merge(df4,df5,how='right',on='emp_id')

emp_id  salary    pf  mob_no  house_no
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [23]:
data6 = {'emp_id1': [101,102,103,104],
         'salary' : [234,345,200,400],
         'pf' : [23,34,56,78] 
         }

data7 = {'emp_id2' : [101,102,104,105],
         'mob_no' : [3434,5656,767,878],
         'house_no' : [345,345,345,56]
         }

df6 = pd.DataFrame(data6)
df7 = pd.DataFrame(data7)

pd.merge(df6,df7,left_on='emp_id1',right_on='emp_id2')

emp_id1  salary  pf  emp_id2  mob_no  house_no
0      101     234  23      101    3434       345
1      102     345  34      102    5656       345
2      104     400  78      104     767       345

In [24]:
data8 = {'emp_id' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         
data9  = {'emp_id' : [101,102,104,105],
          'salary' : [234, 345,200,878],
          'house_nu' : [345,345,345,56]
          }

df8 = pd.DataFrame(data8)
df9 = pd.DataFrame(data9)

pd.merge(df8,df9,on=['emp_id','salary']) #Joining on Multiple Columns

emp_id  salary  pf  house_nu
0     101     234  23       345
1     102     345  34       345

In [25]:
#Join Operations
data10 = {'emp_id1' : [101,102,103,104],
         'salary1' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         
data11  = {'emp_id2' : [101,102,104,105,123],
          'salary2' : [234, 345,200,878,43],
          'house_nu' : [345,345,345,56,234]
          }

df10 = pd.DataFrame(data10,index=['a','b','c','d'])
df11 = pd.DataFrame(data11,index=['a','b','d','e','f'])

df10.join(df11) #Match basis index. It will perform join basis row index whereas in Merge it will join basis column Index

emp_id1  salary1  pf  emp_id2  salary2  house_nu
a      101      234  23    101.0    234.0     345.0
b      102      345  34    102.0    345.0     345.0
c      103      200  56      NaN      NaN       NaN
d      104      400  78    104.0    200.0     345.0

In [29]:
df_sales = pd.read_csv("/content/sample_data/sales_data_final.csv")

In [27]:
def profit_flag(a) :
  if a > 0 :
    return 'positive'
  else :
    return 'negative'

In [28]:
profit_flag(45)

'positive'

In [30]:
#Map,FIlter and Reduce function can be applied on lists but we want to apply such function for Series
df_sales['flag_profit'] = df_sales['profit'].apply(profit_flag) #Applying our function to each row of Dataframe
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sub_category  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...      Storage   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...     Supplies   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...      Storage   
3  Home Office        Stockholm     Sweden      EU    North  ...        Paper   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...  Furnishings   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year flag_profit  
0          35.46          Medium  2011    positive  
1           9.72          Medium  2011    positive  
2           8.17            High  2011    positive  
3           4.82            High  2011    negative  
4           4.70          Medium  2011    positive  

[5 rows x 22 columns]

In [31]:
df_sales['len_cust_name'] = df_sales['customer_name'].apply(len) #Applying inbuilt function
df_sales

order_id  order_date ship_date       ship_mode  \
0         AG-2011-2040    1/1/2011  1/6/2011  Standard Class   
1        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
2         HU-2011-1220    1/1/2011  1/5/2011    Second Class   
3      IT-2011-3647632    1/1/2011  1/5/2011    Second Class   
4        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
...                ...         ...       ...             ...   
51285   CA-2014-115427  12/31/2014  1/4/2015  Standard Class   
51286     MO-2014-2560  12/31/2014  1/5/2015  Standard Class   
51287   MX-2014-110527  12/31/2014  1/2/2015    Second Class   
51288   MX-2014-114783  12/31/2014  1/6/2015  Standard Class   
51289   CA-2014-156720  12/31/2014  1/4/2015  Standard Class   

          customer_name      segment             state        country  market  \
0       Toby Braunhardt     Consumer       Constantine        Algeria  Africa   
1           Joseph Holt     Consumer   New South Wales      Australia    APAC   
2         Annie Thurman     Consumer          Budapest        Hungary    EMEA   
3          Eugene Moren  Home Office         Stockholm         Sweden      EU   
4           Joseph Holt     Consumer   New South Wales      Australia    APAC   
...                 ...          ...               ...            ...     ...   
51285        Erica Bern    Corporate        California  United States      US   
51286         Liz Preis     Consumer  Souss-Massa-Draƒ        Morocco  Africa   
51287  Charlotte Melton     Consumer           Managua      Nicaragua   LATAM   
51288     Tamara Dahlen     Consumer         Chihuahua         Mexico   LATAM   
51289     Jill Matthias     Consumer          Colorado  United States      US   

        region  ...                                     product_name sales  \
0       Africa  ...                              Tenex Lockers, Blue   408   
1      Oceania  ...                         Acme Trimmer, High Speed   120   
2         EMEA  ...                          Tenex Box, Single Width    66   
3        North  ...                      Enermax Note Cards, Premium    45   
4      Oceania  ...                       Eldon Light Bulb, Duo Pack   114   
...        ...  ...                                              ...   ...   
51285     West  ...  Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl    14   
51286   Africa  ...          Wilson Jones Hole Reinforcements, Clear     4   
51287  Central  ...           Hon Color Coded Labels, 5000 Label Set    26   
51288    North  ...           Hon Legal Exhibit Labels, Alphabetical     7   
51289     West  ...                              Bagged Rubber Bands     3   

      quantity discount    profit  shipping_cost  order_priority  year  \
0            2      0.0  106.1400          35.46          Medium  2011   
1            3      0.1   36.0360           9.72          Medium  2011   
2            4      0.0   29.6400           8.17            High  2011   
3            3      0.5  -26.0550           4.82            High  2011   
4            5      0.1   37.7700           4.70          Medium  2011   
...        ...      ...       ...            ...             ...   ...   
51285        2      0.2    4.5188           0.89          Medium  2014   
51286        1      0.0    0.4200           0.49          Medium  2014   
51287        3      0.0   12.3600           0.35          Medium  2014   
51288        1      0.0    0.5600           0.20          Medium  2014   
51289        3      0.2   -0.6048           0.17          Medium  2014   

       flag_profit len_cust_name  
0         positive            15  
1         positive            11  
2         positive            13  
3         negative            12  
4         positive            11  
...            ...           ...  
51285     positive            10  
51286     positive             9  
51287     positive            16  
51288     positive            13  
51289     negative            13  

[51290 rows x 23 columns]

In [32]:
def quanity_flag(a):
  if a<10:
    return 'low'
  elif a>10 and a<20:
    return 'medium'
  else:
    return 'high'

df_sales['flag_quantity'] = df_sales['quantity'].apply(quanity_flag)
df_sales 

order_id  order_date ship_date       ship_mode  \
0         AG-2011-2040    1/1/2011  1/6/2011  Standard Class   
1        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
2         HU-2011-1220    1/1/2011  1/5/2011    Second Class   
3      IT-2011-3647632    1/1/2011  1/5/2011    Second Class   
4        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
...                ...         ...       ...             ...   
51285   CA-2014-115427  12/31/2014  1/4/2015  Standard Class   
51286     MO-2014-2560  12/31/2014  1/5/2015  Standard Class   
51287   MX-2014-110527  12/31/2014  1/2/2015    Second Class   
51288   MX-2014-114783  12/31/2014  1/6/2015  Standard Class   
51289   CA-2014-156720  12/31/2014  1/4/2015  Standard Class   

          customer_name      segment             state        country  market  \
0       Toby Braunhardt     Consumer       Constantine        Algeria  Africa   
1           Joseph Holt     Consumer   New South Wales      Australia    APAC   
2         Annie Thurman     Consumer          Budapest        Hungary    EMEA   
3          Eugene Moren  Home Office         Stockholm         Sweden      EU   
4           Joseph Holt     Consumer   New South Wales      Australia    APAC   
...                 ...          ...               ...            ...     ...   
51285        Erica Bern    Corporate        California  United States      US   
51286         Liz Preis     Consumer  Souss-Massa-Draƒ        Morocco  Africa   
51287  Charlotte Melton     Consumer           Managua      Nicaragua   LATAM   
51288     Tamara Dahlen     Consumer         Chihuahua         Mexico   LATAM   
51289     Jill Matthias     Consumer          Colorado  United States      US   

        region  ... sales quantity discount    profit shipping_cost  \
0       Africa  ...   408        2      0.0  106.1400         35.46   
1      Oceania  ...   120        3      0.1   36.0360          9.72   
2         EMEA  ...    66        4      0.0   29.6400          8.17   
3        North  ...    45        3      0.5  -26.0550          4.82   
4      Oceania  ...   114        5      0.1   37.7700          4.70   
...        ...  ...   ...      ...      ...       ...           ...   
51285     West  ...    14        2      0.2    4.5188          0.89   
51286   Africa  ...     4        1      0.0    0.4200          0.49   
51287  Central  ...    26        3      0.0   12.3600          0.35   
51288    North  ...     7        1      0.0    0.5600          0.20   
51289     West  ...     3        3      0.2   -0.6048          0.17   

       order_priority  year  flag_profit  len_cust_name flag_quantity  
0              Medium  2011     positive             15           low  
1              Medium  2011     positive             11           low  
2                High  2011     positive             13           low  
3                High  2011     negative             12           low  
4              Medium  2011     positive             11           low  
...               ...   ...          ...            ...           ...  
51285          Medium  2014     positive             10           low  
51286          Medium  2014     positive              9           low  
51287          Medium  2014     positive             16           low  
51288          Medium  2014     positive             13           low  
51289          Medium  2014     negative             13           low  

[51290 rows x 24 columns]

In [33]:
df_sales['square_quantity'] = df_sales['quantity'].apply(lambda a : a**2)
df_sales

order_id  order_date ship_date       ship_mode  \
0         AG-2011-2040    1/1/2011  1/6/2011  Standard Class   
1        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
2         HU-2011-1220    1/1/2011  1/5/2011    Second Class   
3      IT-2011-3647632    1/1/2011  1/5/2011    Second Class   
4        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
...                ...         ...       ...             ...   
51285   CA-2014-115427  12/31/2014  1/4/2015  Standard Class   
51286     MO-2014-2560  12/31/2014  1/5/2015  Standard Class   
51287   MX-2014-110527  12/31/2014  1/2/2015    Second Class   
51288   MX-2014-114783  12/31/2014  1/6/2015  Standard Class   
51289   CA-2014-156720  12/31/2014  1/4/2015  Standard Class   

          customer_name      segment             state        country  market  \
0       Toby Braunhardt     Consumer       Constantine        Algeria  Africa   
1           Joseph Holt     Consumer   New South Wales      Australia    APAC   
2         Annie Thurman     Consumer          Budapest        Hungary    EMEA   
3          Eugene Moren  Home Office         Stockholm         Sweden      EU   
4           Joseph Holt     Consumer   New South Wales      Australia    APAC   
...                 ...          ...               ...            ...     ...   
51285        Erica Bern    Corporate        California  United States      US   
51286         Liz Preis     Consumer  Souss-Massa-Draƒ        Morocco  Africa   
51287  Charlotte Melton     Consumer           Managua      Nicaragua   LATAM   
51288     Tamara Dahlen     Consumer         Chihuahua         Mexico   LATAM   
51289     Jill Matthias     Consumer          Colorado  United States      US   

        region  ... quantity discount    profit shipping_cost order_priority  \
0       Africa  ...        2      0.0  106.1400         35.46         Medium   
1      Oceania  ...        3      0.1   36.0360          9.72         Medium   
2         EMEA  ...        4      0.0   29.6400          8.17           High   
3        North  ...        3      0.5  -26.0550          4.82           High   
4      Oceania  ...        5      0.1   37.7700          4.70         Medium   
...        ...  ...      ...      ...       ...           ...            ...   
51285     West  ...        2      0.2    4.5188          0.89         Medium   
51286   Africa  ...        1      0.0    0.4200          0.49         Medium   
51287  Central  ...        3      0.0   12.3600          0.35         Medium   
51288    North  ...        1      0.0    0.5600          0.20         Medium   
51289     West  ...        3      0.2   -0.6048          0.17         Medium   

       year  flag_profit  len_cust_name  flag_quantity square_quantity  
0      2011     positive             15            low               4  
1      2011     positive             11            low               9  
2      2011     positive             13            low              16  
3      2011     negative             12            low               9  
4      2011     positive             11            low              25  
...     ...          ...            ...            ...             ...  
51285  2014     positive             10            low               4  
51286  2014     positive              9            low               1  
51287  2014     positive             16            low               9  
51288  2014     positive             13            low               1  
51289  2014     negative             13            low               9  

[51290 rows x 25 columns]

# **NUMPY PACKAGE**

In [35]:
import numpy as np #Matlab Functions converted into a python library: Numerical Python

In [36]:
np.array([2,3,4,5,6]) #Converted List into numpy array

array([2, 3, 4, 5, 6])

In [37]:
type(np.array([2,3,4,5,6]) ) #1D Array

numpy.ndarray

In [38]:
np.array([[2,3,4],[4,5,6]]) #2D Array

array([[2, 3, 4],
       [4, 5, 6]])

In [ ]:
np.array([[1,2,3,4],[2,3,4,5]]) #2D Array

In [40]:
#Extracting Data from List
l = [[1,2,3,4],[2,3,4,5]]
print(l[0][0])
print(l[1][3]) 

1
5


In [42]:
#Similarily it will happen for array as above. Extracting data from Array
a = np.array([[1,2,3,4],[2,3,4,5]])
print(a[0][0])
print(a[1][3]) 

1
5


In [44]:
a = np.array([3,4,5,6],ndmin=5)
a #5 Brackets in the begining and end (5 dimensions)

array([[[[[3, 4, 5, 6]]]]])

In [48]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr) #2 dimension array as x axis index 0,1,2 and y index 0,1,2. So we can represent data in 2 axis, Hence 2D
arr.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [ ]:
#Matrices is subset of array

In [49]:
np.random.randint(1,10,(4,4)) #4,4 is 4 rows and 4 columns and the random numbers will be between 1 and 10

array([[6, 6, 3, 1],
       [3, 2, 5, 1],
       [9, 7, 7, 8],
       [3, 5, 5, 8]])

In [50]:
#3D data as we will be able to represent this data using 3 axis
np.random.randint(1,10,(4,4,2)) #3 brackets beg and 3 at end: we will have 4*2 dimensions(4 rows and 2 columns) 4 times

array([[[5, 5],
        [2, 6],
        [9, 4],
        [4, 4]],

       [[7, 7],
        [5, 8],
        [7, 7],
        [8, 7]],

       [[8, 4],
        [3, 9],
        [7, 1],
        [6, 3]],

       [[7, 9],
        [2, 1],
        [6, 9],
        [4, 5]]])

# **TASKS:**
https://drive.google.com/drive/folders/1zRQjEqbUWCIrBOk3rqMXI_5luwfN0QnY

In [ ]:
#Task 1 - Fitbit Dataset

1. Read this dataset in pandas , mysql and mongodb 
2. while creting a table in mysql dont use manual approach to create it  ,always use a automation to create a table in mysql
 ## hint - use csvkit library to automate this task and to load a data in bulk in you mysql 
3. convert all the dates avaible in dataset to timestamp format in pandas and in sql you to convert it in date format
4 . Find out in this data that how many unique id's we have 
5 . which id is one of the active id that you have in whole dataset 
6 . how many of them have not logged there activity find out in terms of number of ids 
7 . Find out who is the laziest person id that we have in dataset 
8 . Explore over an internet that how much calories burn is required for a healthy person and find out how many healthy person we have in our dataset 
9. how many person are not a regular person with respect to activity try to find out those 
10 . who is the thired most active person in this dataset find out those in pandas and in sql both . 
11 . who is the 5th most laziest person avilable in dataset find it out 
12 . what is a totla acumulative calories burn for a person find out 


In [ ]:
#task 2 - Superstore_USA
1 . load this data in sql and in pandas with a relation in sql 
2 . while loading this data you dont have to create a table manually you can use any automated approach to create a table and load a data in bulk in table 
3 . Find out how return that we ahve recived and with a product id 
4 . try  to join order and return data both in sql and pandas 
5 . Try to find out how many unique customer that we have 
6 . try to find out in how many regions we are selling a product and who is a manager for a respective region 
7 . find out how many different differnet shipement mode that we have and what is a percentage usablity of all the shipment mode with respect to dataset 
8 . Create a new coulmn and try to find our a diffrence between order date and shipment date
9 . base on question number 8 find out for which order id we have shipment duration more than 10 days 
10 . Try to find out a list of a returned order which sihpment duration was more then 15 days and find out that region manager as well 
11 . Gorup by region and find out which region is more profitable 
12 . Try to find out overalll in which country we are giving more didscount 
13 . Give me a list of unique postal code 
14 . which customer segement is more profitalble find it out . 
15 . try to find out the 10th most loss making product catagory . 
16 . Try to find out 10 top  product with highest margins 

submit your git link for the same 
 
you have to submit this task by next Friday 5th 11PM IST  to respective mail id 
sudhanshu@ineuron.ai , sunny.savita@ineuron.ai 
